### ISSUE TITLE
How to setup docker-compose with the current application

### ISSUE THREAD

**Issue by amulyaparmar** [lspahija/AIUI#38]
Hi lsphaija! This is a really awesome project.

Quick question, is there any way you could potentially help provide some guidance to setup with docker-compose up --build?

**Comment by lspahija** [comment]
Here is GPT-4's response to your question:



Hi there!

Certainly! Using `docker-compose` can simplify the process of building and running the application, especially if you have multiple services or configurations. Here's how you can set up AIUI using `docker-compose`:

1. **Create a `docker-compose.yml` File**:

You can create a `docker-compose.yml` file in the root directory of the AIUI repository. Here's an example configuration:

```yaml
version: '3'

services:
  aiui:
    build:
      context: .
      dockerfile: Dockerfile
      # Uncomment the following line if you're on an arm64 architecture
      # platforms: 
      #   - linux/arm64
    image: aiui:latest
    environment:
      - OPENAI_API_KEY=<YOUR_API_KEY>
      - TTS_PROVIDER=EDGETTS
      - EDGETTS_VOICE=en-US-EricNeural
    ports:
      - "8000:80"
```

2. **Build and Run using `docker-compose`**:

With the above `docker-compose.yml` file in place, you can build and run the AIUI application using a single command:

```bash
docker-compose up --build
```

3. **Navigate to the Application**:

Once the application is up and running, you can navigate to `localhost:8000` in a modern browser, just like before.

That's it! This `docker-compose` setup should make it easier to manage the AIUI application, especially if you decide to add more services or configurations in the future.
